<?php
// Si l'utilisateur n'est pas 'technicien' on le renvoie au tableau de bord
if(!is_technicien()){
	header('location:index.php');
}
?>

<section class="container">
    <form class="formulaire" action="ajout-photos.php" method="post" enctype="multipart/form-data">
        <fieldset>
                <legend>Ajout de photos</legend>

<!-- Formulaire d'ajout d'opération -->
            <p class="row-desk">
                <label class="col-desk-2" for="photo">Photo :</label>
                <input class="col-desk-10" id="photo" name="photo" type="file" value="" required>
            </p>
            <p class="row-desk">
                <label class="col-desk-2" for="titre">Titre :</label>
                <input class="col-desk-10" id="titre" name="titre" type="text" value="" required>
            </p>            
            <button class="btn" type="submit">Ajouter</button>
            <button class="btn" type="button"><a href="ajout-notes.php">Passer cette étape</a></button>
        </fieldset>        
    </form>    
</section>