<section>
    <?php if (isset($_GET['id'])):?>
    <form class="formulaire" action="modif-gestionnaire.php?id=<?= $_GET['id']?>" method="post">
        <fieldset>
                <legend>Modification d'un gestionnaire</legend>
    <?php else: ?>
    <form class="formulaire" action="ajout-gestionnaire.php" method="post">
        <fieldset>
                <legend>Ajout d'un gestionnaire</legend>
    <?php endif; ?> 
            <p>
                <label for="nom">Nom :</label>
                <input id="nom" name="nom" maxlength="100" type="text" value="<?= $nom ?>" required>
            </p>
            <p>
                <label for="prenom">Prénom :</label>
                <input id="prenom" name="prenom" maxlength="100" type="text" value="<?= $prenom ?>" required>
            </p>
            <p>
                <label for="email">Email :</label>
                <input id="email" name="email" maxlength="100" type="email" value="<?= $email ?>" required>
            </p>
            <p>
                <label for="mdp">Mot de passe :</label>
                <input id="mdp" name="mdp" maxlength="50" type="password" value="<?= $mdp ?>" required>
            </p>
            <?php if (isset($_GET['id'])):?>
            <button class="btn" type="submit">Modifier</button>
            <?php else: ?>
            <button class="btn" type="submit">Ajouter</button>
            <?php endif; ?>             
        </fieldset>        
    </form>    
</section>