<?php
// Si l'utilisateur n'est pas 'technicien' on le renvoie au tableau de bord
if(!is_technicien()){
	header('location:index.php');
}
?>

<section class="container">
    <form class="formulaire" action="ajout-notes.php" method="post">
        <fieldset>
                <legend>Ajout de notes</legend>

<!-- Formulaire d'ajout d'opération -->
            <p class="row-desk">
                <label class="col-desk-2" for="note">Note :</label>
                <textarea name="note" id="note" cols="30" rows="10" required></textarea>
            </p>            
            <button class="btn" type="submit">Ajouter</button>
            <button class="btn" type="button"><a href="liste-operations.php">Passer cette étape</a></button>
        </fieldset>        
    </form>    
</section>