<!-- Si l'utilisateur n'est pas 'gestionnaire' ou 'technicien' on le renvoie au tableau de bord -->
<?php
if(!is_gestionnaire() && !is_technicien()){
	header('location:index.php');
}
?>

<!-- Sinon on affiche le détail du véhicule -->
<h1>Détail du véhicule</h1>
<section class="container">
    <table class="table tableList">
        <tr>
            <th>Id</th>
            <td><?= $vehicule['id'] ?></td>
        </tr>
        <tr>
            <th>Type</th>
            <td><?= $vehicule['type'] ?></td>
        </tr>
        <tr>
            <th>Marque</th>
            <td><?= $vehicule['marque'] ?></td>
        </tr>
        <tr>
            <th>Modèles</th>
            <td><?= $vehicule['modele'] ?></td>
        </tr>
        <tr>
            <th>Date d'achat</th>
            <td><?= strftime("%d %h %Y", strtotime($vehicule['date_achat']));?></td>
        </tr>
        <tr>
            <th>Problème</th>
            <td class="pb<?=$vehicule['id'] ?>">
                    <?php if($vehicule['probleme']==''):?>
                    Pas de problème
                    <?php else: ?>
                    <?= $vehicule['probleme'] ?>
                    <?php endif ?>
            </td>
        </tr>
        <?php if(is_gestionnaire()):?>       
        <tr>
            <th>Actions</th>            
            <td>                
                <a class="btn" href="modif-vehicule.php?id=<?=$vehicule['id'] ?>">Modifier</a> - 
                <span class="supprVehicule btn" data-id="<?= $vehicule['id'] ?>">Supprimer</span>                
            </td>
        </tr>
        <?php endif ?>
        <?php if(is_technicien() && $vehicule['probleme']!=''):?>
        <tr class="actionPb">
            <th>Actions</th> 
            <td>
                <span class="pbResolu btn" data-id="<?= $vehicule['id'] ?>">Problème résolu ?</span>
            </td>
        </tr>
        <?php endif ?>        
    </table>
</section>

<h1>Liste des opérations en cours</h1>
<section class="container">
    <?php if(is_technicien()):?>
    <a class="btn ib" href="ajout-operation.php">Ajouter une opération</a>
    <?php endif; ?>
    <?php if(empty($operation)): ?>
    <p>Pas d'opérations en cours</p>
    <?php else:?>
    <table class="table">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr class="<?= $operation['id'] ?>">
                <td><?= $operation['sujet'] ?></td>
                <td><?= $operation['marque'] ?></td>
                <td><?= $operation['modele'] ?></td>                
                <td>
                    <?php if(is_technicien()):?>
                    <a class="btn" href="modif-operation.php?id=<?=$operation['id'] ?>">Modifier</a> - 
                    <?php endif; ?>
                    <a class="btn" href="detail-operation.php?id=<?=$operation['id'] ?>">Détail</a>
                </td>
            </tr>
        </tbody>
    </table>
    <?php endif;?>
</section>
<h1>Liste des opérations à venir</h1>
<section class="container">   
    <?php if(empty($prevu)): ?>
    <p>Pas d'opérations prévues</p>
    <?php else:?>
    <table class="table tableList">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr class="<?= $prevu['id'] ?>">
                <td><?= $prevu['sujet'] ?></td>
                <td><?= $prevu['marque'] ?></td>
                <td><?= $prevu['modele'] ?></td>                
                <td>
                    <?php if(is_technicien()):?>
                    <a class="btn" href="modif-operation.php?id=<?=$operation['id'] ?>">Modifier</a> - 
                    <?php endif; ?>
                    <a class="btn" href="detail-operation.php?id=<?=$prevu['id'] ?>">Détail</a>
                </td>
            </tr>
        </tbody>
    </table>
    <?php endif; ?>
</section>

<h1>Liste des opérations passées</h1>
<section class="container">    
    <?php if(empty($historique)): ?>
    <p>Pas d'opérations passées</p>
    <?php else:?>
    <table class="table tableList">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr class="<?= $historique['id'] ?>">
                <td><?= $historique['sujet'] ?></td>
                <td><?= $historique['marque'] ?></td>
                <td><?= $historique['modele'] ?></td>                
                <td>
                    <a class="btn" href="detail-operation.php?id=<?=$historique['id'] ?>">Détail</a>
                </td>
            </tr>
        </tbody>
    </table>
    <?php endif; ?>
</section>