<!-- Si l'utilisateur n'est pas 'gestionnaire' ou 'technicien' on le renvoie au tableau de bord -->
<?php
if(!is_gestionnaire() && !is_technicien()){
	header('location:index.php');
}
?>

<!-- Sinon on affiche le détail du véhicule -->
<section class="container">
    <h1>Détail du véhicule</h1>
    <table class="table">
        <tr>
            <th>Id</th>
            <td><?= $vehicule['id'] ?></td>
        </tr>
        <tr>
            <th>Type</th>
            <td><?= $vehicule['type'] ?></td>
        </tr>
        <tr>
            <th>Marque</th>
            <td><?= $vehicule['marque'] ?></td>
        </tr>
        <tr>
            <th>Modèles</th>
            <td><?= $vehicule['modele'] ?></td>
        </tr>
        <tr>
            <th>Date d'achat</th>
            <td><?= strftime("%d %h %Y", strtotime($vehicule['date_achat']));?></td>
        </tr>
        <tr>
            <th>Problème</th>
            <td class="pb<?=$vehicule['id'] ?>">
                    <?php if($vehicule['probleme']==''):?>
                    Pas de problème
                    <?php else: ?>
                    <?= $vehicule['probleme'] ?>
                    <?php endif ?>
            </td>
        </tr>
        <?php if(is_gestionnaire()):?>       
        <tr>
            <th>Actions</th>            
            <td>                
                <a href="modif-vehicule.php?id=<?=$vehicule['id'] ?>">Modifier</a> - 
                <span class="supprVehicule" data-id="<?= $vehicule['id'] ?>">Supprimer</span>                
            </td>
        </tr>
        <?php endif ?>
        <?php if(is_technicien() && $vehicule['probleme']!=''):?>
        <tr class="actionPb">
            <th>Actions</th> 
            <td>
                <span class="pbResolu" data-id="<?= $vehicule['id'] ?>">Problème résolu ?</span>
            </td>
        </tr>
        <?php endif ?>        
    </table>
</section>