<!-- Si l'utilisateur n'est pas 'technicien' on le renvoie au tableau de bord -->
<?php
if(!is_technicien()){
	header('location:index.php');
}
?>

<!-- Sinon on affiche le détail du véhicule -->
<h1>Détail de l'opération</h1>
<section class="container">
    <table class="table tableList">
        <tr>
            <th>Id</th>
            <td><?= $operation['id'] ?></td>
        </tr>
        <tr>
            <th>Marque</th>
            <td><?= $operation['marque'] ?></td>
        </tr>
        <tr>
            <th>Modèles</th>
            <td><?= $operation['modele'] ?></td>
        </tr>
        <tr>
            <th>Sujet</th>
            <td><?= $operation['sujet'] ?></td>
        </tr>
        <tr>
            <th>Date de début</th>
            <td><?= strftime("%d %h %Y", strtotime($operation['date_debut']));?></td>
        </tr>
        <tr>
            <th>Date de fin</th>
            <td><?= strftime("%d %h %Y", strtotime($operation['date_fin']));?></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><?= $operation['description'] ?></td>
        </tr>
        <tr>
            <th>Actions</th>
            <td>                
                <a class="btn" href="modif-operation.php?id=<?=$operation['id'] ?>">Modifier</a>               
            </td>
        </tr>
    </table>
</section>
<section class="photos">
    <?php foreach ($photos as $photo):?>
    <h2><?= $photo['titre'] ?></h2>
    <img src="img/<?= $photo['photo'] ?>" alt="<?= $photo['titre'] ?>">
    <?php endforeach; ?>
</section>
<section class="notes container">
    <h2>Note(s) :</h2>    
    <?php foreach ($notes as $note):?>
    <p>
        <span class="underline">De : <?= $note['prenom'] ?> <?= $note['nom'] ?></span><br>
        <?= $note['note'] ?>
    </p>
    <?php endforeach; ?>
</section>
<section class="pieces container">    
    <h2>Liste de pièce(s) :</h2>
    <ul>
        <?php foreach ($pieces as $piece):?>
        <li><?= $piece['nom'] ?> - Quantité : <?= $piece['quantite'] ?></li>
        <?php endforeach; ?>
    </ul>    
</section>