<?php if(isset($_SESSION['user'])): ?>

<h1>Tableau de bord</h1>

<?php else: ?>
<h1>Système de gestion de maintenance</h1>
<?php if(isset($message)){echo $message; } ?>
<form action="index.php" method="post">
    <input type="text" name='login' placeholder="Votre identifiant">
    <input type="password" name="mdp" placeholder="Votre mot de passe">
    <button>Se connecter</button>
</form>

<?php endif; ?>