<!-- Affichage du tableau de bord si l'utilisateur est connecté -->
<?php if(is_connect()): ?>
<section>
    <h1>Tableau de bord</h1>
    <article class="container">
        <h2>Bienvenue <?= $_SESSION['user']?> </h2>
        <p><a class="btn" href="php/deconnect.php">Déconnexion</a></p>
    </article>
</section>

<div class="container row-desk">
<section class="col-desk-6">
    <article>
    <h2>Etat des véhicules</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Problème</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($vehicules as $vehicule):?>
            <tr>
                <td><?= $vehicule['marque'] ?></td>
                <td><?= $vehicule['modele'] ?></td>
                <td>
                    <?php if($vehicule['probleme']==''):?>
                    Pas de problème
                    <?php else: ?>
                    <?= $vehicule['probleme'] ?>
                    <?php endif ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </article>
    <article>
    <h2>Liste des opérations en cours</h2>
    <?php if(empty($operations)): ?>
    <p>Pas d'opérations en cours</p>
    <?php else:?>
    <table class="table">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($operations as $operation):?>
            <tr class="<?= $operation['id'] ?>">
                <td><?= $operation['sujet'] ?></td>
                <td><?= $operation['marque'] ?></td>
                <td><?= $operation['modele'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif;?>
    </article>
    <article>
    <h2>Liste des opérations à venir</h2> 
    <?php if(empty($prevus)): ?>
    <p>Pas d'opérations prévues</p>
    <?php else:?>
    <table class="table">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($prevus as $prevu):?>
            <tr class="<?= $prevu['id'] ?>">
                <td><?= $prevu['sujet'] ?></td>
                <td><?= $prevu['marque'] ?></td>
                <td><?= $prevu['modele'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
    </article>
    
</section>
<section class='col-desk-6'>
    <h2>Activités sur les 30 derniers jours</h2>
    <div id="chartContainer"></div>
</section>
</div>
<script>
window.onload = function () {
 
var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	exportEnabled: true,
	title:{
		text: "Intervention sur les 30 derniers jours"
	},
	subtitles: [{
		text: "En nombre d'intervention"
	}],
	data: [{
		type: "pie",
		showInLegend: "true",
		legendText: "{label}",
		indexLabelFontSize: 16,
		indexLabel: "{label} - #percent%",
		yValueFormatString: "",
		dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
	}]
});
chart.render();
$('.canvasjs-chart-credit').text('');
$('.canvasjs-chart-toolbar').text('');
}
</script>

 <!-- Sinon on affiche la page de connexion -->   
<?php else: ?>
<h1>Système de gestion de maintenance</h1>
<section class="container">
    <?php if(isset($message)){echo $message; } ?>
    <form class='formulaire' action="index.php" method="post">
        <fieldset class="connexionForm">
            <legend>Connexion</legend>
            <p class="row-desk">
                <label class="col-desk-4" for="login">Login :</label>
                <input class="col-desk-8" id='login' type="text" name='login' placeholder="Votre email">
            </p>
            <p class="row-desk">
                <label class="col-desk-4" for="mdp">Mot de passe :</label>
                <input class="col-desk-8" id='mdp' type="password" name="mdp" placeholder="Votre mot de passe">
            </p>
            <p class="align-center">                
                <button class="btn">Se connecter</button>
            </p>
        </fieldset>            
    </form>
</section>
<?php endif; ?>