<?php
// Si l'utilisation n'est pas 'administrateur' on le renvoie au tableau de bord
if(!isset($_SESSION['administrateur'])){
	header('location:index.php');
}
?>
  
<section class="container">
    <?php if ($_GET['role']=='gestionnaire'):?>
    <h1>Liste des gestionnaires</h1>
    <a href="ajout-user.php?role=gestionnaire">Ajouter un gestionnaire</a>
    <?php elseif ($_GET['role']=='technicien'):?> 
    <h1>Liste des techniciens</h1>
    <a href="ajout-user.php?role=technicien">Ajouter un technicien</a>
    <?php endif;?>
    <table class="table">
        <thead>
            <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($_GET['role']=='gestionnaire'):?>
            <?php foreach($gestionnaires as $gestionnaire):?>
            <tr>
                <td><?= $gestionnaire['id'] ?></td>
                <td><?= $gestionnaire['nom'] ?></td>
                <td><?= $gestionnaire['prenom'] ?></td>
                <td><?= $gestionnaire['email'] ?></td>
                <td>
                    <a href="modif-user.php?id=<?=$gestionnaire['id'] ?>&amp;role=gestionnaire">Modifier</a> - 
                    <a href="suppr-user.php?id=<?=$gestionnaire['id'] ?>&amp;role=gestionnaire">Supprimer</a>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php elseif ($_GET['role']=='technicien'):?> 
            <?php foreach($techniciens as $technicien):?>
            <tr>
                <td><?= $technicien['id'] ?></td>
                <td><?= $technicien['nom'] ?></td>
                <td><?= $technicien['prenom'] ?></td>
                <td><?= $technicien['email'] ?></td>
                <td>
                    <a href="modif-user.php?id=<?=$technicien['id'] ?>&amp;role=technicien">Modifier</a> - 
                    <a href="suppr-user.php?id=<?=$technicien['id'] ?>&amp;role=technicien">Supprimer</a>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif;?>
            </tbody>
        </table>
</section>