<!-- Si l'utilisateur n'est pas 'gestionnaire' on le renvoie au tableau de bord -->
<?php
if(!is_technicien()){
	header('location:index.php');
}
?>


<!-- Sinon on affiche le tableau des opérations -->
<h1>Liste des opérations en cours</h1>
<section class="container">
    <a class="btn ib" href="ajout-operation.php">Ajouter une opération</a>
    <?php if(empty($operations)): ?>
    <p>Pas d'opérations en cours</p>
    <?php else:?>
    <table class="table">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($operations as $operation):?>
            <tr class="<?= $operation['id'] ?>">
                <td><?= $operation['sujet'] ?></td>
                <td><?= $operation['marque'] ?></td>
                <td><?= $operation['modele'] ?></td>                
                <td>
                    <a class="btn" href="modif-operation.php?id=<?=$operation['id'] ?>">Modifier</a> - 
                    <a class="btn" href="detail-operation.php?id=<?=$operation['id'] ?>">Détails</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif;?>
</section>
<h1>Liste des opérations à venir</h1>
<section class="container">  
    <?php if(empty($prevus)): ?>
    <p>Pas d'opérations prévues</p>
    <?php else:?>
    <table class="table">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($prevus as $prevu):?>
            <tr class="<?= $prevu['id'] ?>">
                <td><?= $prevu['sujet'] ?></td>
                <td><?= $prevu['marque'] ?></td>
                <td><?= $prevu['modele'] ?></td>                
                <td>
                    <a class="btn" href="modif-operation.php?id=<?=$prevu['id'] ?>">Modifier</a> - 
                    <a class="btn" href="detail-operation.php?id=<?=$prevu['id'] ?>">Détails</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</section>
<h1>Liste des opérations passées</h1> 
<section class="container">   
    <?php if(empty($historiques)): ?>
    <p>Pas d'opérations passées</p>
    <?php else:?>
    <table class="table">
        <thead>
            <tr>
                <th>Sujet</th>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($historiques as $historique):?>
            <tr class="<?= $historique['id'] ?>">
                <td><?= $historique['sujet'] ?></td>
                <td><?= $historique['marque'] ?></td>
                <td><?= $historique['modele'] ?></td>                
                <td>
                    <a class="btn" href="detail-operation.php?id=<?=$historique['id'] ?>">Détails</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</section>