<!-- Si l'utilisateur n'est pas 'administrateur' on le renvoie au tableau de bord -->
<?php
if(!is_administrateur()){
	header('location:index.php');
}
?>

<!-- Sinon on affiche le tableau des gestionnaire ou des technicien en fonction du lien cliqué -->

<?php if ($_GET['role']=='gestionnaire'):?>
<h1>Liste des gestionnaires</h1>
<section class="container">
    <a class="btn ib" href="ajout-user.php?role=gestionnaire">Ajouter un gestionnaire</a>
    <?php elseif ($_GET['role']=='technicien'):?>
    <h1>Liste des techniciens</h1>
    <section class="container">
        <a class="btn ib" href="ajout-user.php?role=technicien">Ajouter un technicien</a>
        <?php endif;?>
        <table class="table tableList">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($_GET['role']=='gestionnaire'):?>
                <?php foreach($gestionnaires as $gestionnaire):?>
                <tr class="<?= $gestionnaire['id'] ?>">
                    <td><?= $gestionnaire['id'] ?></td>
                    <td><?= $gestionnaire['nom'] ?></td>
                    <td><?= $gestionnaire['prenom'] ?></td>
                    <td><?= $gestionnaire['email'] ?></td>
                    <td>
                        <a class="btn" href="modif-user.php?id=<?=$gestionnaire['id'] ?>&amp;role=gestionnaire">Modifier</a> -
                        <span class="supprUser btn" data-id="<?= $gestionnaire['id'] ?>">Supprimer</span>
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php elseif ($_GET['role']=='technicien'):?>
                <?php foreach($techniciens as $technicien):?>
                <tr class="<?= $technicien['id'] ?>">
                    <td><?= $technicien['id'] ?></td>
                    <td><?= $technicien['nom'] ?></td>
                    <td><?= $technicien['prenom'] ?></td>
                    <td><?= $technicien['email'] ?></td>
                    <td>
                        <a class="btn" href="modif-user.php?id=<?=$technicien['id'] ?>&amp;role=technicien">Modifier</a> -
                        <span class="supprUser btn" data-id="<?= $technicien['id'] ?>">Supprimer</span>
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php endif;?>
            </tbody>
        </table>
    </section>