<!-- Si l'utilisateur n'est pas 'gestionnaire' on le renvoie au tableau de bord -->
<?php
if(!is_gestionnaire() && !is_technicien()){
	header('location:index.php');
}
?>


<!-- Sinon on affiche le tableau des véhicules -->
<section class="container">
    <h1>Liste des véhicules</h1>
    <?php if(is_gestionnaire()){
        echo ('<a href="ajout-vehicule.php">Ajouter un véhicule</a>');
    }
    ?>    
    <table class="table">
        <thead>
            <tr>
                <th>Marque</th>
                <th>Modèle</th>
                <th>Problème</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($vehicules as $vehicule):?>
            <tr>
                <td><?= $vehicule['marque'] ?></td>
                <td><?= $vehicule['modele'] ?></td>
                <td class="pb<?=$vehicule['id'] ?>">
                    <?php if($vehicule['probleme']==''):?>
                    Pas de problème
                    <?php else: ?>
                    <?= $vehicule['probleme'] ?>
                    <?php endif ?>
                </td>
                <td>
                    <?php if(is_gestionnaire()):?>
                    <a href="modif-vehicule.php?id=<?=$vehicule['id'] ?>">Modifier - </a>
                    <span class="supprVehicule" data-id="<?= $vehicule['id'] ?>">Supprimer - </span>
                    <?php endif ?>
                    <a href="detail-vehicule.php?id=<?=$vehicule['id'] ?>">Détail</a>
                    <?php if(is_technicien()):?>
                    <span class="ajoutPb" data-id="<?= $vehicule['id'] ?>"> - Signaler un problème</span>
                    <?php endif ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>