<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?></title>
    <meta name="description" content="">

    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body class="">
    <?php if(isset($_SESSION['user'])): ?>
    <header>
      <nav class="container-fluid fixed">
        <ul id="mainmenu" class="row-desk">          
          <?php if(is_administrateur()): ?>
          <li class="col-desk-4 align-center"><a class="active" href="index.php">Tableau de bord</a></li>
          <li class="col-desk-4 align-center"><a class="" href="liste-user.php?role=gestionnaire">Liste des gestionnaires</a></li>
          <li class="col-desk-4 align-center"><a class="" href="liste-user.php?role=technicien">Liste des techniciens</a></li>
          <?php endif; ?>
          <?php if(is_gestionnaire()): ?>
          <li class="col-desk-4 align-center"><a class="active" href="index.php">Tableau de bord</a></li>
          <li class="col-desk-4 align-center"><a class="" href="liste-vehicules.php">Liste des véhicules</a>
          <li class="col-desk-4 align-center"><a class="" href="ajout-vehicule.php">Ajouter un véhicule</a>
          <?php endif; ?>
          <?php if(is_technicien()): ?>
          <li class="col-desk-3 align-center"><a class="active" href="index.php">Tableau de bord</a></li>
          <li class="col-desk-3 align-center"><a class="" href="liste-vehicules.php">Liste des véhicules</a>
          <li class="col-desk-3 align-center"><a class="" href="liste-operations.php">Liste des opérations de maintenance</a></li>
          <li class="col-desk-3 align-center"><a class="" href="ajout-operation.php">Ajouter une opération de maintenance</a></li>
          <?php endif; ?>
        </ul>
      </nav>
    </header>
    <?php endif; ?>

    <main>
          <?php include 'templates/'.$template.'.phtml'; ?>
    </main>

    <footer>  
      <p class="copyright align-center">Projet Webreathe 2019 - Site réalisé par Laurent PICHON <a href="https://www.devlawper.com" target="_blank">Dev{L@w}per</a></p>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="js/sticky-nav.js"></script>
    <script src="js/actions.js"></script>    
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
  </body>
</html>